# Generated by Django 3.2.7 on 2023-01-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0013_auto_20230101_2041'),
        ('profiles', '0002_company_customer_district_salesstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='meter_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meters.metermanagement'),
        ),
    ]
