# Generated by Django 3.2.7 on 2023-01-01 18:31

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230101_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=base.fields.SUBField(blank=True, max_length=20, null=True),
        ),
    ]
