# Generated by Django 3.2.7 on 2022-12-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0004_metermanagement_meter_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('is_paid', models.BooleanField(default='False')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meters.metermanagement')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meters.meterreading')),
                ('unit_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meters.unitrate')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=55, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.billing')),
            ],
        ),
    ]
