# Generated by Django 3.2.7 on 2022-12-10 14:34

import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='billing',
            new_name='bill',
        ),
        migrations.AddField(
            model_name='billing',
            name='billing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=base.fields.SUBField(blank=True, max_length=20, null=True),
        ),
    ]
