# Generated by Django 3.2.7 on 2022-12-13 22:02

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20221210_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_code',
            field=base.fields.SUBField(blank=True, max_length=20, null=True),
        ),
    ]
