# Generated by Django 3.2.7 on 2023-01-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0012_auto_20230101_0346'),
        ('billing', '0003_billing_bill_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='payment_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meters.metermanagement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
