#!/bin/bash

##this script puppose ensures that we get conected on the database service before we spin any other service in container

##if any command on code fails for any reason, then the entire shell script fails
set -o errexit

##fail exit if one of pipe commands fails
set -o pipefail

##this exits if any of variables is not set
set -o nounset

##declare postgres
postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",

    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Waiting for PostgreSQL to become available....:-("
 sleep 1
done
>&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"