# Generated by Django 3.2.7 on 2022-10-26 12:15

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterManagement',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Site Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Meter Reference Code')),
                ('description', models.TextField(default='Default description...update me please....', verbose_name='Description')),
                ('country', django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Nairobi', max_length=180, verbose_name='City')),
                ('postal_code', models.CharField(default='140', max_length=100, verbose_name='Postal Code')),
                ('street_address', models.CharField(default='KG8 Avenue', max_length=150, verbose_name='Street Address')),
                ('meter_number', models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meter Number')),
                ('meter_type', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Smart', 'Smart')], default='Mechanical', max_length=50, verbose_name='Meter Type')),
                ('site_type', models.CharField(choices=[('Building', 'Building'), ('Farm', 'Farm'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Property Type')),
                ('initial_reading', models.IntegerField(default=0, verbose_name='Initial Meter Reading')),
                ('current_reading', models.IntegerField(default=0, verbose_name='Current Meter Reading')),
                ('read_status', models.BooleanField(default=False, verbose_name='Reading Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Site Manager,Meter Reader or Customer')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
            },
        ),
    ]
