# Generated by Django 3.2.7 on 2022-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metermanagement',
            name='site_type',
            field=models.CharField(choices=[('Building', 'Building'), ('Farm', 'Farm'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Site Type'),
        ),
    ]
