# Generated by Django 3.2.7 on 2022-11-29 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0002_alter_metermanagement_site_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff_date', models.DateField(verbose_name='Effective Date')),
            ],
            options={
                'verbose_name': 'Usage Rate',
                'verbose_name_plural': 'Usage Rates',
            },
        ),
        migrations.AlterField(
            model_name='metermanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meter_owner', to=settings.AUTH_USER_MODEL, verbose_name='Site Manager,Meter Reader or Customer'),
        ),
        migrations.CreateModel(
            name='UnitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Rate')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meters.metermanagement')),
                ('usage_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meters.usagerate')),
            ],
            options={
                'verbose_name': 'Unit Rate',
                'verbose_name_plural': 'Unit Rates',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reading', models.PositiveIntegerField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meters.metermanagement')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meter_read', to=settings.AUTH_USER_MODEL, verbose_name='Meter Reader')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
            },
        ),
    ]
