# Generated by Django 3.2.7 on 2022-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_auto_20221129_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='metermanagement',
            name='meter_reading',
            field=models.IntegerField(default=0, verbose_name='Current Meter Reading'),
        ),
    ]
