# Generated by Django 3.2.7 on 2022-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_metermanagement_meter_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metermanagement',
            name='meter_reading',
            field=models.IntegerField(default=0),
        ),
    ]
