# Generated by Django 3.2.7 on 2022-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_metermanagement_meter_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterMutation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_reading', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('litre_usage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('end_reading', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meters.metermanagement')),
            ],
            options={
                'ordering': ('timestamp', 'pk'),
            },
        ),
    ]
