# Generated by Django 3.2.7 on 2022-12-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_metermutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metermanagement',
            name='current_reading',
        ),
        migrations.RemoveField(
            model_name='metermanagement',
            name='initial_reading',
        ),
        migrations.RemoveField(
            model_name='metermanagement',
            name='meter_reading',
        ),
        migrations.AlterField(
            model_name='metermutation',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='meters.metermanagement'),
        ),
    ]
