# Generated by Django 3.2.7 on 2022-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0009_auto_20221214_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='metermanagement',
            name='initial_reading',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
