# Generated by Django 3.2.7 on 2023-01-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0013_auto_20230101_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='metermanagement',
            name='pricing_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meters.pricingcategory'),
        ),
    ]
