# Generated by Django 3.2.7 on 2022-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indices',
            },
        ),
    ]
